export enum JewelType {
  GLORIOUS_VANITY = 'Glorious Vanity',
  LETHAL_PRIDE = 'Lethal Pride',
  BRUTAL_RESTRAINT = 'Brutal Restraint',
  MILITANT_FAITH = 'Militant Faith',
  ELEGANT_HUBRIS = 'Elegant Hubris',
}

export const jewelTypes = Object.values(JewelType);

const GLORIOUS_VANITY_VARIANTS = [
  'base_fire_damage_resistance_%',
  'base_maximum_fire_damage_resistance_%',
  'base_lightning_damage_resistance_%',
  'mana_regeneration_rate_+%',
  'base_maximum_lightning_damage_resistance_%',
  'cold_damage_+%',
  'base_reduce_enemy_cold_resistance_%',
  'base_life_leech_from_cold_damage_permyriad',
  'base_cold_damage_resistance_%',
  'base_movement_velocity_+%',
  'chaos_damage_+%',
  'withered_on_hit_for_2_seconds_%_chance',
  'attack_damage_+%',
  'maximum_life_+%',
  'spell_damage_+%',
  'projectile_damage_+%',
  'area_damage_+%',
  'base_chance_to_shock_%',
  'base_chance_to_freeze_%',
  'maximum_energy_shield_+%',
  'critical_strike_chance_+%',
  'fire_damage_+%',
  'evasion_rating_+%',
  'spell_critical_strike_chance_+%',
  'physical_damage_reduction_rating_+%',
  'base_chaos_damage_resistance_%',
  'base_maximum_chaos_damage_resistance_%',
  'maximum_mana_+%',
  'lightning_damage_+%',
  'base_life_leech_from_lightning_damage_permyriad',
  'curse_effect_+%',
  'base_chance_to_ignite_%',
  'damage_over_time_+%',
  'base_additional_physical_damage_reduction_%',
  'physical_damage_+%',
  'non_curse_aura_effect_+%',
  'base_life_leech_from_physical_damage_permyriad',
  'base_spell_block_%',
  'base_spell_suppression_chance_%',
  'base_resist_all_elements_%',
  'attack_speed_+%',
  'shield_armour_+%',
  'curse_skill_effect_duration_+%',
  'base_critical_strike_multiplier_+',
  'chance_to_deal_double_damage_%',
  'base_life_leech_from_attack_damage_permyriad',
  'minion_damage_+%',
  'avoid_all_elemental_status_%',
  'base_avoid_stun_%',
  'base_life_leech_from_fire_damage_permyriad',
  'skill_effect_duration_+%',
  'life_regeneration_rate_per_minute_%',
  'faster_bleed_%',
  'base_cast_speed_+%',
  'minion_maximum_life_+%',
  'additional_block_%',
  'base_projectile_speed_+%',
  'base_skill_area_of_effect_+%',
  'base_energy_shield_leech_from_spell_damage_permyriad',
  'base_reduce_enemy_fire_resistance_%',
  'base_physical_damage_%_to_convert_to_fire',
  'base_aura_area_of_effect_+%',
  'base_physical_damage_%_to_convert_to_cold',
  'life_gained_on_block',
  'base_physical_damage_%_to_convert_to_lightning',
  'global_chance_to_blind_on_hit_%',
  'base_life_leech_from_chaos_damage_permyriad',
  'base_maximum_cold_damage_resistance_%',
  'base_reduce_enemy_lightning_resistance_%',
  'energy_shield_recharge_rate_+%'
];

const LETHAL_PRIDE_VARIANTS = [
  'warcry_buff_effect_+%',
  'base_strength',
  'strength_+%',
  'maximum_life_+%',
  'physical_damage_reduction_rating_+%',
  'base_max_fortification',
  'physical_damage_taken_%_as_fire',
  'burn_damage_+%',
  'physical_damage_+%',
  'base_fire_damage_resistance_%',
  'melee_critical_strike_chance_+%',
  'totem_damage_+%',
  'faster_burn_%',
  'summon_totem_cast_speed_+%',
  'base_self_critical_strike_multiplier_-%',
  'life_regeneration_rate_per_minute_%',
  'base_stun_duration_+%',
  'base_stun_threshold_reduction_+%',
  'melee_damage_+%',
  'melee_weapon_critical_strike_multiplier_+',
  'chance_to_intimidate_on_hit_%',
  'physical_damage_%_to_add_as_fire',
  'endurance_charge_on_kill_%',
  'chance_to_deal_double_damage_%',
  'base_life_leech_from_attack_damage_permyriad'
];

const BRUTAL_RESTRAINT_VARIANTS = [
  'base_poison_damage_+%',
  'base_dexterity',
  'accuracy_rating_+%',
  'critical_strike_chance_+%',
  'charges_gained_+%',
  'base_elemental_status_ailment_duration_+%',
  'base_movement_velocity_+%',
  'global_chance_to_blind_on_hit_%',
  'attack_and_cast_speed_+%',
  'base_avoid_stun_%',
  'minion_movement_speed_+%',
  'maximum_life_+%',
  'onslaught_buff_duration_on_kill_ms',
  'evasion_rating_+%',
  'elemental_damage_+%',
  'dexterity_+%',
  'minion_damage_+%',
  'non_curse_aura_effect_+%',
  'projectile_damage_+%',
  'gain_alchemists_genius_on_flask_use_%',
  'base_cold_damage_resistance_%',
  'non_damaging_ailment_effect_+%',
  'physical_damage_%_to_add_as_cold',
  'faster_poison_%',
  'add_frenzy_charge_on_kill_%_chance'
];

const MILITANT_FAITH_VARIANTS = [
  'base_devotion',
  'inflict_lightning_exposure_on_hit_%_chance_at_devotion_threshold',
  'gain_arcane_surge_on_hit_at_devotion_threshold',
  'minimum_power_charges_at_devotion_threshold',
  'inflict_fire_exposure_on_hit_%_chance_at_devotion_threshold',
  'immune_to_elemental_ailments_while_on_consecrated_ground_at_devotion_threshold',
  'physical_damage_%_to_convert_to_lightning_at_devotion_threshold',
  'mana_%_to_add_as_energy_shield_at_devotion_threshold',
  'physical_damage_%_to_convert_to_cold_at_devotion_threshold',
  'additional_maximum_all_resistances_%_at_devotion_threshold',
  'minimum_frenzy_charges_at_devotion_threshold',
  'inflict_cold_exposure_on_hit_%_chance_at_devotion_threshold',
  'physical_damage_reduction_%_at_devotion_threshold',
  'minimum_endurance_charges_at_devotion_threshold',
  'physical_damage_%_to_convert_to_fire_at_devotion_threshold'
];

const ELEGANT_HUBRIS_VARIANTS = [
  'physical_damage_+%',
  'base_spell_block_%',
  'maximum_life_+%',
  'minion_damage_+%',
  'cold_damage_with_attack_skills_+%',
  'physical_damage_reduction_rating_+%_per_endurance_charge',
  'non_curse_aura_effect_+%',
  'spell_damage_+%',
  'base_lightning_damage_resistance_%',
  'base_chaos_damage_resistance_%',
  'projectile_attack_damage_+%',
  'minion_maximum_life_+%',
  'base_avoid_shock_%',
  'flask_duration_+%',
  'mana_regeneration_rate_+%',
  'accuracy_rating_+%',
  'gain_endurance_charge_per_second_if_have_been_hit_recently',
  'avoid_all_elemental_status_%',
  'base_avoid_chill_%',
  'damage_+%_per_frenzy_charge',
  'critical_strike_chance_+%',
  'base_critical_strike_multiplier_+',
  'base_item_found_rarity_+%',
  'additional_block_%',
  'bleeding_damage_+%',
  'faster_bleed_%',
  'chill_effect_+%',
  'base_spell_suppression_chance_%',
  'base_fire_damage_resistance_%',
  'evasion_rating_+%',
  'energy_shield_+%_per_power_charge',
  'base_cold_damage_resistance_%',
  'physical_damage_reduction_rating_+%',
  'melee_physical_damage_+%',
  'maximum_mana_+%',
  'attack_speed_+%',
  'shock_effect_+%',
  'evasion_rating_+%_per_frenzy_charge',
  'add_frenzy_charge_on_skill_hit_%',
  'base_cast_speed_+%',
  'damage_+%_per_endurance_charge',
  'damage_+%_per_power_charge',
  'spell_critical_strike_chance_+%',
  'add_power_charge_on_critical_strike_%',
  'lightning_damage_with_attack_skills_+%',
  'fire_damage_with_attack_skills_+%'
];

export const variants = {
  [JewelType.GLORIOUS_VANITY]: GLORIOUS_VANITY_VARIANTS,
  [JewelType.LETHAL_PRIDE]: LETHAL_PRIDE_VARIANTS,
  [JewelType.BRUTAL_RESTRAINT]: BRUTAL_RESTRAINT_VARIANTS,
  [JewelType.MILITANT_FAITH]: MILITANT_FAITH_VARIANTS,
  [JewelType.ELEGANT_HUBRIS]: ELEGANT_HUBRIS_VARIANTS,
};
